apiVersion: v1
kind: ConfigMap
metadata:
  name: opsflow-config
  namespace: opsflow
data:
  LOG_LEVEL: "info"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "opsflow"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  OLLAMA_BASE_URL: "http://ollama:11434"
  LLM_DEFAULT_PROVIDER: "mock"
